name: Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Set Git user name and email
        run: |
          git config --local user.name "chaosskill"
          git config --local user.email "chaosskill@gmail.com"

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Make a commit
        run: |
          echo "New commit" >> README.md
          git add README.md
          git commit -m "Auto commit $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push
