name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *' # run at midnight every day

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update file
        run: echo "Update $(date)" >> README.md

      - name: Commit changes
        run: |
          git config --global user.email "chaosskill@gmail.com"
          git config --global user.name "chaosskill"
          git commit -m "Update $(date)" -a
          git push